FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    netcat-openbsd curl procps && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY notification.py /app/notification.py

EXPOSE 8080

CMD ["python3", "/app/notification.py"]
