events {
    worker_connections 1024;
}

http {
    upstream webapp_pool {
        server 10.88.0.11:8080;
        server 10.88.0.12:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://webapp_pool;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header User-Agent $http_user_agent;
        }

        location /health {
            return 200 'OK';
            add_header Content-Type text/plain;
        }
    }
}
